version: '2'

services:
  cappuchaino:
    build: .
    stdin_open: true
    tty: true
    ports:
      - "7447:7447"
      - "8000:8000"
    expose:
      - 7447
      - 8000
    environment:
      CHAINNAME: cafeauchain
      NETWORK_PORT: 7447
      RPC_PORT: 8000
      RPC_USER: multichainrpc
      RPC_PASSWORD: this-is-insecure-change-it
      RPC_ALLOW_IP: 0.0.0.0/0.0.0.0
      PARAM_ANYONE_CAN_RECEIVE: anyone-can-receive|true
      PARAM_ANYONE_CAN_SEND: anyone-can-send|true
      PARAM_ANYONE_CAN_ISSUE: anyone-can-issue|true
      PARAM_ANYONE_CAN_CONNECT: anyone-can-connect|true
      PARAM_ANYONE_CAN_MINE: anyone-can-mine|true
